import { StyleSheet } from 'react-native';
import * as Colors from '../../styling/colors';

export const styles = StyleSheet.create({
  body: {
    color: Colors.GRAYSCALE_BODY,
    fontFamily: 'OpenSans-Regular',
    fontSize: 12,
    lineHeight: 16,
    marginLeft: 24,
    marginRight: 24,
    marginTop: 12,
    textAlign: 'center',
  },
  container: {
    backgroundColor: Colors.PROMPT_BACKGROUND,
    borderRadius: 14,
    marginLeft: 24,
    marginRight: 24,
    maxWidth: 280,
  },
  primaryCta: {
    alignItems: 'center',
    color: Colors.GRAYSCALE_BLACK,
    flex: 1,
    fontFamily: 'OpenSans-Bold',
    fontSize: 12,
    justifyContent: 'center',
    textAlign: 'center',
  },
  primaryCtaContainer: {
    alignItems: 'center',
    borderStyle: 'solid',
    borderTopColor: Colors.GRAYSCALE_LINE,
    borderTopWidth: 1,
    flex: 1,
    flexDirection: 'row',
    height: 48,
    marginTop: 28,
    maxHeight: 48,
    minHeight: 48,
  },
  primaryCtaContainerPressed: {
    backgroundColor: Colors.TRANSPARENT_BLACK,
  },
  secondaryCta: {
    alignItems: 'center',
    color: Colors.GRAYSCALE_BLACK,
    flex: 1,
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 12,
    justifyContent: 'center',
    textAlign: 'center',
  },
  secondaryCtaContainer: {
    alignItems: 'center',
    borderStyle: 'solid',
    borderTopColor: Colors.GRAYSCALE_LINE,
    borderTopWidth: 1,
    flex: 1,
    flexDirection: 'row',
    height: 48,
    maxHeight: 48,
    minHeight: 48,
  },
  secondaryCtaContainerPressed: {
    backgroundColor: Colors.TRANSPARENT_BLACK,
  },
  title: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 16,
    lineHieght: 22,
    marginLeft: 24,
    marginRight: 24,
    marginTop: 28,
    textAlign: 'center',
  },
});
