import { StyleSheet } from 'react-native';
import * as Colors from '../../../../styling/colors';

export const styles = StyleSheet.create({
  container: {},
  backgroundContainer: {},
  background: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  content: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
  },
  contentWrapper: {},
  header: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 60,
    backgroundColor: Colors.NEW_GRAYSCALE_DARK_GRAY,
    paddingLeft: 0,
    paddingRight: 0,
    alignSelf: 'stretch',
  },
  headerLeft: {
    flexBasis: 44,
    flexGrow: 1,
    flexDirection: 'row',
    alignItems: 'stretch',
    justifyContent: 'flex-start',
    alignSelf: 'stretch',
  },
  back: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingLeft: 12,
    paddingRight: 12,
  },
  headerCenter: {
    flexBasis: 'auto',
    flexGrow: 0,
  },
  headerText: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 20,
    textAlign: 'center',
    color: Colors.PRIMARY_LIGHT,
  },
  headerRight: {
    flexBasis: 44,
    flexGrow: 1,
    flexShrink: 1,
  },
  contentInner: {
    alignItems: 'stretch',
    justifyContent: 'flex-start',
    paddingTop: 24,
  },
  title: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 20,
    textAlign: 'left',
    color: Colors.PRIMARY_LIGHT,
  },
  statusDetails: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 12,
    textAlign: 'left',
    marginTop: 8,
    color: Colors.GRAYSCALE_MID_GRAY,
  },
  upgradeContainer: {
    marginTop: 24,
  },
  lifetimeProps: {
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    marginTop: 24,
  },
  lifetimePropsTitle: {
    fontFamily: 'OpenSans-SemiBold',
    fontSize: 28,
    textAlign: 'left',
    color: Colors.WHITE,
  },
  valueProps: {
    alignItems: 'stretch',
    justifyContent: 'flex-start',
    marginTop: 16,
    gap: 8,
  },
  valueProp: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  valuePropIcon: {
    marginRight: 8,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    width: 24,
    height: 24,
    fontSize: 17,
  },
  valuePropText: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 17,
    textAlign: 'left',
    color: Colors.PRIMARY_LIGHT,
  },
  storeInfo: {
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    marginTop: 24,
  },
  storeInfoTitle: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    textAlign: 'left',
    color: Colors.PRIMARY_LIGHT,
  },
  storeInfoDetailsList: {
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    marginTop: 8,
    gap: 4,
  },
  storeInfoDetailsListItem: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    textAlign: 'left',
    color: Colors.GRAYSCALE_MID_GRAY,
  },
  storeInfoDetailsListItemLink: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'baseline',
  },
  storeInfoDetailsListItemLinkText: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    textAlign: 'left',
    color: Colors.GRAYSCALE_MID_GRAY,
    textDecorationColor: Colors.GRAYSCALE_MID_GRAY,
    textDecorationLine: 'underline',
  },
});
