import { Platform, StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  content: {
    flex: 1,
    alignItems: 'stretch',
    justifyContent: 'center',
  },
  header: {
    color: 'white',
    fontFamily: 'OpenSans-Regular',
    fontSize: 24,
    lineHeight: 32,
    textAlign: 'center',
    paddingLeft: 24,
    paddingRight: 24,
    maxWidth: 390,
    marginBottom: 40,
  },
  continueWithGoogleContainer: {
    paddingLeft: 24,
    paddingRight: 24,
    maxWidth: 390,
    flex: 1,
    alignItems: 'stretch',
    justifyContent: 'center',
    maxHeight: 56,
    marginBottom: 32,
  },
  continueWithGoogle: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    maxHeight: 56,
    borderRadius: 100,
    backgroundColor: '#446266',

    ...Platform.select({
      ios: {
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
      },
      android: {
        elevation: 20,
        shadowColor: '#000000',
      },
    }),
  },
  continueWithGooglePressed: {
    backgroundColor: '#33494c',
  },
  google: {
    width: 16,
    height: 16,
    marginRight: 12,
  },
  continueWithGoogleText: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.25,
    color: 'white',
  },
  continueWithAppleContainer: {
    paddingLeft: 24,
    paddingRight: 24,
    maxWidth: 390,
    flex: 1,
    alignItems: 'stretch',
    justifyContent: 'center',
    maxHeight: 56,
    marginBottom: 60,
  },
  continueWithApple: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    maxHeight: 56,
    borderRadius: 100,
    borderWidth: 2,
    borderStyle: 'solid',
    borderColor: '#FFFFFF',
  },
  continueWithApplePressed: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  apple: {
    width: 18,
    height: 18,
    marginRight: 12,
  },
  continueWithAppleText: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    lineHeight: 24,
    letterSpacing: 0.25,
    color: 'white',
  },
  legalContainer: {
    paddingLeft: 24,
    paddingRight: 24,
    maxWidth: 240,
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  legal: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 12,
    lineHeight: 20,
    textAlign: 'center',
    letterSpacing: 0.15,
    color: '#FFFFFF',
  },
});
