import { StyleSheet } from 'react-native';
import * as Colors from '../../styling/colors';

export const styles = StyleSheet.create({
  bottomContainer: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-end',
  },
  bottomDescription: {
    color: Colors.GRAYSCALE_LIGHT_GRAY,
    fontFamily: 'OpenSans-Regular',
    fontSize: 12,
    letterSpacing: 0.15,
    lineHeight: 20,
    maxWidth: 225,
    paddingBottom: 70,
    textAlign: 'center',
  },
  bottomDescriptionFree: {
    color: Colors.GRAYSCALE_LIGHT_GRAY,
    fontFamily: 'OpenSans-Regular',
    fontSize: 12,
    letterSpacing: 0.15,
    lineHeight: 20,
    maxWidth: 225,
    paddingBottom: 32,
    textAlign: 'center',
  },
  bottomDots: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    height: 8,
    justifyContent: 'center',
    maxHeight: 8,
  },
  bottomInstructor: {
    color: Colors.TRANSPARENT_LIGHT_GRAY,
    fontFamily: 'OpenSans-Light',
    fontSize: 12,
    lineHeight: 16,
    paddingBottom: 16,
    textAlign: 'center',
  },
  bottomTitle: {
    color: Colors.WHITISH_BLUE,
    fontFamily: 'OpenSans-Regular',
    fontSize: 22,
    lineHeight: 30,
    paddingBottom: 6,
    textAlign: 'center',
  },
  container: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
    paddingBottom: 60,
    paddingLeft: 24,
    paddingRight: 24,
    paddingTop: 40,
  },
  firstDot: {
    height: 8,
    maxHeight: 8,
    maxWidth: 8,
    width: 8,
  },
  header: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    maxHeight: 48,
    maxWidth: 392,
  },
  headerName: {
    color: Colors.WHITE,
    fontFamily: 'OpenSans-Regular',
    fontSize: 12,
    letterSpacing: 0.15,
    lineHeight: 20,
  },
  headerText: {
    alignItems: 'flex-start',
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'center',
  },
  headerTitle: {
    color: Colors.WHITE,
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    letterSpacing: 0.25,
    lineHeight: 28,
  },
  nonFirstDot: {
    height: 8,
    maxHeight: 8,
    maxWidth: 20,
    paddingLeft: 12,
    width: 20,
  },
  profileImage: {
    borderRadius: 24,
    marginRight: 19,
  },
});
