import { StyleSheet } from 'react-native';
import * as Colors from '../../../styling/colors';

export const styles = StyleSheet.create({
  container: {
    position: 'relative',
  },
  background: {
    position: 'absolute',
    top: 0,
    left: 0,
  },
  backgroundOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  content: {
    justifyContent: 'space-between',
    alignItems: 'stretch',
    flexBasis: 0,
  },
  closeButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingTop: 4,
    paddingRight: 16,
  },
  closeButtonInnerContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.GRAYSCALE_MID_GRAY,
    borderRadius: 7.5,
  },
  closeButton: {
    padding: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pausePlayControlContainer: {
    position: 'absolute',
    top: 100,
    left: 0,
    right: 0,
    bottom: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pausePlayControlLoaded: {
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
  },
  footer: {
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  footerInnerContainer: {
    justifyContent: 'center',
    alignItems: 'stretch',
  },
  transcript: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  infoAndActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  info: {
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    flexGrow: 0,
    flexShrink: 1,
    flexBasis: 'auto',
  },
  instructor: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'left',
    color: Colors.GRAYSCALE_MID_GRAY,
  },
  title: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 22,
    textAlign: 'left',
    color: Colors.PRIMARY_LIGHT,
  },
  numClasses: {
    backgroundColor: '#383a34',
    paddingHorizontal: 6,
    color: Colors.PRIMARY_LIGHT,
    fontFamily: 'OpenSans-Regular',
    fontSize: 16,
    textAlign: 'left',
    borderRadius: 4,
    marginTop: 5,
  },
  actions: {
    alignItems: 'flex-end',
    justifyContent: 'flex-start',
    flexGrow: 1,
    flexShrink: 0,
    flexBasis: 'auto',
    paddingLeft: 12,
    gap: 16,
  },
  actionIconsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 8,
  },
  viewDetailsContainer: {
    alignSelf: 'stretch',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  actionIcon: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewDetailsContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewDetailsArrow: {
    marginLeft: 8,
  },
  progressContainer: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    justifyContent: 'center',
    alignItems: 'center',
  },
  progressFull: {
    height: 3,
    backgroundColor: Colors.PRIMARY_LIGHT,
    flexGrow: 0,
    flexShrink: 0,
  },
  progressDot: {
    width: 8,
    height: 8,
    marginLeft: -4,
    marginRight: -4,
    borderRadius: 4,
    flexGrow: 0,
    flexShrink: 0,
    backgroundColor: Colors.PRIMARY_LIGHT,
  },
  progressEmpty: {
    height: 3,
    backgroundColor: Colors.MORE_TRANSPARENT_WHITE,
    flexGrow: 1,
  },
  durationContainer: {
    marginTop: 4,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  currentTime: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 12,
    color: Colors.GRAYSCALE_MID_GRAY,
  },
  totalTime: {
    fontFamily: 'OpenSans-Regular',
    fontSize: 12,
    color: Colors.GRAYSCALE_MID_GRAY,
  },
});
